export const data = [
    {name:"Mark", value: 90},
    {name:"Robert", value: 12},
    {name:"Emily", value: 34},
    {name:"Marion", value: 53},
    {name:"Nicolas", value: 98},
    {name:"Mel", value: 23},
    {name:"Gabriel", value: 18},
    {name:"Jean", value: 104},
    {name:"Sophie", value: 14},
    {name:"Leane", value: 74},
    {name:"Melanie", value: 72},
    {name:"Tibo", value: 23},
    {name:"Remi", value: 124},
    {name:"Balkis", value: 23},
    {name:"Nina", value: 104},
    {name:"Lucas", value: 94},
    {name:"Paul", value: 2},
]
