export type Variable =
  | 'ML Ops'
  | 'Data Pipelines'
  | 'Database'
  | 'Data Viz'
  | 'Storytelling'
  | 'Business Insights'
  | 'Reporting'
  | 'Experimentation'
  | 'Stats'
  | 'ML Modeling'
  | 'Deployment';

export type DataItem<T extends string> = {
  [key in T]: number;
} & {
  name: string;
};

export type Data = DataItem<Variable>[];

export const data: Data = [
  {
    'ML Ops': 3.9,
    'Data Pipelines': 5,
    Database: 5,
    'Data Viz': 2,
    Storytelling: 1.5,
    'Business Insights': 1.5,
    Reporting: 2.2,
    Experimentation: 1.5,
    Stats: 1.5,
    'ML Modeling': 2,
    Deployment: 2.8,
    name: 'Data Engineer',
  },
  {
    'ML Ops': 5,
    'Data Pipelines': 3,
    Database: 3,
    'Data Viz': 1.5,
    Storytelling: 1.5,
    'Business Insights': 1.5,
    Reporting: 2,
    Experimentation: 4,
    Stats: 4,
    'ML Modeling': 4.8,
    Deployment: 5,
    name: 'ML Engineer',
  },
  {
    'ML Ops': 3,
    'Data Pipelines': 1.9,
    Database: 2.8,
    'Data Viz': 3.5,
    Storytelling: 3.3,
    'Business Insights': 3.3,
    Reporting: 3.3,
    Experimentation: 4.7,
    Stats: 5,
    'ML Modeling': 5,
    Deployment: 3.5,
    name: 'Data Scientist',
  },
  {
    'ML Ops': 1.5,
    'Data Pipelines': 1.5,
    Database: 2.5,
    'Data Viz': 5,
    Storytelling: 5,
    'Business Insights': 5,
    Reporting: 5,
    Experimentation: 3.5,
    Stats: 3,
    'ML Modeling': 2.5,
    Deployment: 1.5,
    name: 'Data Analyst',
  },
];

// Source: https://reviewnprep.com/blog/data-engineer-vs-data-analyst-vs-data-scientist-salary-skills-background/
// https://www.glassdoor.com/Salaries/machine-learning-engineer-salary-SRCH_KO0,25.htm
export const dumbelData = [
  { name: 'Data Analyst', value1: 90, value2: 200 },
  { name: 'Data Scientist', value1: 60, value2: 114 },
  { name: 'ML Engineer', value1: 75, value2: 150 },
  { name: 'Data Engineer', value1: 125, value2: 220 },
];

export const timeseriesData = [
  {
    Month: '2016-01',
    'Data Scientist': 13,
    'Data Engineer': 3,
    'Data Analyst': 15,
    'ML Engineer': 0,
  },
  {
    Month: '2016-02',
    'Data Scientist': 12,
    'Data Engineer': 3,
    'Data Analyst': 16,
    'ML Engineer': 0,
  },
  {
    Month: '2016-03',
    'Data Scientist': 12,
    'Data Engineer': 3,
    'Data Analyst': 14,
    'ML Engineer': 0,
  },
  {
    Month: '2016-04',
    'Data Scientist': 12,
    'Data Engineer': 3,
    'Data Analyst': 14,
    'ML Engineer': 0,
  },
  {
    Month: '2016-05',
    'Data Scientist': 15,
    'Data Engineer': 3,
    'Data Analyst': 15,
    'ML Engineer': 0,
  },
  {
    Month: '2016-06',
    'Data Scientist': 13,
    'Data Engineer': 3,
    'Data Analyst': 16,
    'ML Engineer': 0,
  },
  {
    Month: '2016-07',
    'Data Scientist': 12,
    'Data Engineer': 3,
    'Data Analyst': 15,
    'ML Engineer': 0,
  },
  {
    Month: '2016-08',
    'Data Scientist': 12,
    'Data Engineer': 3,
    'Data Analyst': 16,
    'ML Engineer': 0,
  },
  {
    Month: '2016-09',
    'Data Scientist': 15,
    'Data Engineer': 4,
    'Data Analyst': 17,
    'ML Engineer': 0,
  },
  {
    Month: '2016-10',
    'Data Scientist': 13,
    'Data Engineer': 4,
    'Data Analyst': 16,
    'ML Engineer': 0,
  },
  {
    Month: '2016-11',
    'Data Scientist': 14,
    'Data Engineer': 4,
    'Data Analyst': 16,
    'ML Engineer': 0,
  },
  {
    Month: '2016-12',
    'Data Scientist': 13,
    'Data Engineer': 3,
    'Data Analyst': 12,
    'ML Engineer': 0,
  },
  {
    Month: '2017-01',
    'Data Scientist': 15,
    'Data Engineer': 4,
    'Data Analyst': 17,
    'ML Engineer': 0,
  },
  {
    Month: '2017-02',
    'Data Scientist': 16,
    'Data Engineer': 5,
    'Data Analyst': 19,
    'ML Engineer': 0,
  },
  {
    Month: '2017-03',
    'Data Scientist': 16,
    'Data Engineer': 5,
    'Data Analyst': 19,
    'ML Engineer': 0,
  },
  {
    Month: '2017-04',
    'Data Scientist': 14,
    'Data Engineer': 5,
    'Data Analyst': 18,
    'ML Engineer': 0,
  },
  {
    Month: '2017-05',
    'Data Scientist': 16,
    'Data Engineer': 5,
    'Data Analyst': 17,
    'ML Engineer': 0,
  },
  {
    Month: '2017-06',
    'Data Scientist': 16,
    'Data Engineer': 5,
    'Data Analyst': 19,
    'ML Engineer': 0,
  },
  {
    Month: '2017-07',
    'Data Scientist': 17,
    'Data Engineer': 5,
    'Data Analyst': 21,
    'ML Engineer': 0,
  },
  {
    Month: '2017-08',
    'Data Scientist': 17,
    'Data Engineer': 6,
    'Data Analyst': 20,
    'ML Engineer': 0,
  },
  {
    Month: '2017-09',
    'Data Scientist': 18,
    'Data Engineer': 6,
    'Data Analyst': 19,
    'ML Engineer': 0,
  },
  {
    Month: '2017-10',
    'Data Scientist': 19,
    'Data Engineer': 6,
    'Data Analyst': 22,
    'ML Engineer': 0,
  },
  {
    Month: '2017-11',
    'Data Scientist': 18,
    'Data Engineer': 6,
    'Data Analyst': 21,
    'ML Engineer': 0,
  },
  {
    Month: '2017-12',
    'Data Scientist': 16,
    'Data Engineer': 5,
    'Data Analyst': 16,
    'ML Engineer': 0,
  },
  {
    Month: '2018-01',
    'Data Scientist': 20,
    'Data Engineer': 6,
    'Data Analyst': 23,
    'ML Engineer': 0,
  },
  {
    Month: '2018-02',
    'Data Scientist': 20,
    'Data Engineer': 7,
    'Data Analyst': 22,
    'ML Engineer': 0,
  },
  {
    Month: '2018-03',
    'Data Scientist': 21,
    'Data Engineer': 6,
    'Data Analyst': 26,
    'ML Engineer': 0,
  },
  {
    Month: '2018-04',
    'Data Scientist': 20,
    'Data Engineer': 6,
    'Data Analyst': 23,
    'ML Engineer': 0,
  },
  {
    Month: '2018-05',
    'Data Scientist': 19,
    'Data Engineer': 7,
    'Data Analyst': 27,
    'ML Engineer': 0,
  },
  {
    Month: '2018-06',
    'Data Scientist': 19,
    'Data Engineer': 7,
    'Data Analyst': 25,
    'ML Engineer': 0,
  },
  {
    Month: '2018-07',
    'Data Scientist': 22,
    'Data Engineer': 8,
    'Data Analyst': 26,
    'ML Engineer': 0,
  },
  {
    Month: '2018-08',
    'Data Scientist': 24,
    'Data Engineer': 8,
    'Data Analyst': 26,
    'ML Engineer': 0,
  },
  {
    Month: '2018-09',
    'Data Scientist': 25,
    'Data Engineer': 8,
    'Data Analyst': 27,
    'ML Engineer': 0,
  },
  {
    Month: '2018-10',
    'Data Scientist': 24,
    'Data Engineer': 8,
    'Data Analyst': 27,
    'ML Engineer': 0,
  },
  {
    Month: '2018-11',
    'Data Scientist': 22,
    'Data Engineer': 8,
    'Data Analyst': 26,
    'ML Engineer': 0,
  },
  {
    Month: '2018-12',
    'Data Scientist': 19,
    'Data Engineer': 7,
    'Data Analyst': 22,
    'ML Engineer': 0,
  },
  {
    Month: '2019-01',
    'Data Scientist': 24,
    'Data Engineer': 8,
    'Data Analyst': 29,
    'ML Engineer': 0,
  },
  {
    Month: '2019-02',
    'Data Scientist': 26,
    'Data Engineer': 9,
    'Data Analyst': 29,
    'ML Engineer': 0,
  },
  {
    Month: '2019-03',
    'Data Scientist': 25,
    'Data Engineer': 9,
    'Data Analyst': 30,
    'ML Engineer': 0,
  },
  {
    Month: '2019-04',
    'Data Scientist': 25,
    'Data Engineer': 9,
    'Data Analyst': 29,
    'ML Engineer': 0,
  },
  {
    Month: '2019-05',
    'Data Scientist': 28,
    'Data Engineer': 10,
    'Data Analyst': 29,
    'ML Engineer': 0,
  },
  {
    Month: '2019-06',
    'Data Scientist': 25,
    'Data Engineer': 9,
    'Data Analyst': 31,
    'ML Engineer': 0,
  },
  {
    Month: '2019-07',
    'Data Scientist': 28,
    'Data Engineer': 11,
    'Data Analyst': 34,
    'ML Engineer': 0,
  },
  {
    Month: '2019-08',
    'Data Scientist': 30,
    'Data Engineer': 11,
    'Data Analyst': 34,
    'ML Engineer': 0,
  },
  {
    Month: '2019-09',
    'Data Scientist': 31,
    'Data Engineer': 11,
    'Data Analyst': 34,
    'ML Engineer': 0,
  },
  {
    Month: '2019-10',
    'Data Scientist': 29,
    'Data Engineer': 12,
    'Data Analyst': 34,
    'ML Engineer': 0,
  },
  {
    Month: '2019-11',
    'Data Scientist': 28,
    'Data Engineer': 12,
    'Data Analyst': 32,
    'ML Engineer': 0,
  },
  {
    Month: '2019-12',
    'Data Scientist': 26,
    'Data Engineer': 11,
    'Data Analyst': 29,
    'ML Engineer': 0,
  },
  {
    Month: '2020-01',
    'Data Scientist': 28,
    'Data Engineer': 11,
    'Data Analyst': 35,
    'ML Engineer': 0,
  },
  {
    Month: '2020-02',
    'Data Scientist': 29,
    'Data Engineer': 12,
    'Data Analyst': 34,
    'ML Engineer': 0,
  },
  {
    Month: '2020-03',
    'Data Scientist': 23,
    'Data Engineer': 9,
    'Data Analyst': 27,
    'ML Engineer': 0,
  },
  {
    Month: '2020-04',
    'Data Scientist': 24,
    'Data Engineer': 10,
    'Data Analyst': 26,
    'ML Engineer': 0,
  },
  {
    Month: '2020-05',
    'Data Scientist': 27,
    'Data Engineer': 10,
    'Data Analyst': 30,
    'ML Engineer': 0,
  },
  {
    Month: '2020-06',
    'Data Scientist': 27,
    'Data Engineer': 12,
    'Data Analyst': 32,
    'ML Engineer': 0,
  },
  {
    Month: '2020-07',
    'Data Scientist': 29,
    'Data Engineer': 13,
    'Data Analyst': 35,
    'ML Engineer': 1,
  },
  {
    Month: '2020-08',
    'Data Scientist': 28,
    'Data Engineer': 12,
    'Data Analyst': 33,
    'ML Engineer': 1,
  },
  {
    Month: '2020-09',
    'Data Scientist': 31,
    'Data Engineer': 13,
    'Data Analyst': 35,
    'ML Engineer': 1,
  },
  {
    Month: '2020-10',
    'Data Scientist': 28,
    'Data Engineer': 12,
    'Data Analyst': 33,
    'ML Engineer': 1,
  },
  {
    Month: '2020-11',
    'Data Scientist': 24,
    'Data Engineer': 10,
    'Data Analyst': 29,
    'ML Engineer': 1,
  },
  {
    Month: '2020-12',
    'Data Scientist': 25,
    'Data Engineer': 11,
    'Data Analyst': 30,
    'ML Engineer': 0,
  },
  {
    Month: '2021-01',
    'Data Scientist': 26,
    'Data Engineer': 11,
    'Data Analyst': 33,
    'ML Engineer': 1,
  },
  {
    Month: '2021-02',
    'Data Scientist': 26,
    'Data Engineer': 12,
    'Data Analyst': 35,
    'ML Engineer': 0,
  },
  {
    Month: '2021-03',
    'Data Scientist': 28,
    'Data Engineer': 12,
    'Data Analyst': 37,
    'ML Engineer': 1,
  },
  {
    Month: '2021-04',
    'Data Scientist': 26,
    'Data Engineer': 13,
    'Data Analyst': 37,
    'ML Engineer': 1,
  },
  {
    Month: '2021-05',
    'Data Scientist': 28,
    'Data Engineer': 14,
    'Data Analyst': 39,
    'ML Engineer': 1,
  },
  {
    Month: '2021-06',
    'Data Scientist': 30,
    'Data Engineer': 14,
    'Data Analyst': 43,
    'ML Engineer': 1,
  },
  {
    Month: '2021-07',
    'Data Scientist': 29,
    'Data Engineer': 15,
    'Data Analyst': 43,
    'ML Engineer': 1,
  },
  {
    Month: '2021-08',
    'Data Scientist': 30,
    'Data Engineer': 15,
    'Data Analyst': 43,
    'ML Engineer': 1,
  },
  {
    Month: '2021-09',
    'Data Scientist': 32,
    'Data Engineer': 15,
    'Data Analyst': 45,
    'ML Engineer': 1,
  },
  {
    Month: '2021-10',
    'Data Scientist': 30,
    'Data Engineer': 15,
    'Data Analyst': 43,
    'ML Engineer': 1,
  },
  {
    Month: '2021-11',
    'Data Scientist': 29,
    'Data Engineer': 15,
    'Data Analyst': 42,
    'ML Engineer': 1,
  },
  {
    Month: '2021-12',
    'Data Scientist': 28,
    'Data Engineer': 15,
    'Data Analyst': 44,
    'ML Engineer': 1,
  },
  {
    Month: '2022-01',
    'Data Scientist': 39,
    'Data Engineer': 24,
    'Data Analyst': 64,
    'ML Engineer': 1,
  },
  {
    Month: '2022-02',
    'Data Scientist': 43,
    'Data Engineer': 26,
    'Data Analyst': 70,
    'ML Engineer': 1,
  },
  {
    Month: '2022-03',
    'Data Scientist': 45,
    'Data Engineer': 27,
    'Data Analyst': 72,
    'ML Engineer': 1,
  },
  {
    Month: '2022-04',
    'Data Scientist': 43,
    'Data Engineer': 27,
    'Data Analyst': 71,
    'ML Engineer': 1,
  },
  {
    Month: '2022-05',
    'Data Scientist': 42,
    'Data Engineer': 27,
    'Data Analyst': 70,
    'ML Engineer': 1,
  },
  {
    Month: '2022-06',
    'Data Scientist': 42,
    'Data Engineer': 28,
    'Data Analyst': 74,
    'ML Engineer': 2,
  },
  {
    Month: '2022-07',
    'Data Scientist': 45,
    'Data Engineer': 30,
    'Data Analyst': 77,
    'ML Engineer': 2,
  },
  {
    Month: '2022-08',
    'Data Scientist': 45,
    'Data Engineer': 32,
    'Data Analyst': 79,
    'ML Engineer': 2,
  },
  {
    Month: '2022-09',
    'Data Scientist': 44,
    'Data Engineer': 30,
    'Data Analyst': 82,
    'ML Engineer': 1,
  },
  {
    Month: '2022-10',
    'Data Scientist': 39,
    'Data Engineer': 29,
    'Data Analyst': 75,
    'ML Engineer': 1,
  },
  {
    Month: '2022-11',
    'Data Scientist': 40,
    'Data Engineer': 28,
    'Data Analyst': 75,
    'ML Engineer': 2,
  },
  {
    Month: '2022-12',
    'Data Scientist': 34,
    'Data Engineer': 24,
    'Data Analyst': 64,
    'ML Engineer': 1,
  },
  {
    Month: '2023-01',
    'Data Scientist': 43,
    'Data Engineer': 29,
    'Data Analyst': 86,
    'ML Engineer': 2,
  },
  {
    Month: '2023-02',
    'Data Scientist': 41,
    'Data Engineer': 31,
    'Data Analyst': 88,
    'ML Engineer': 2,
  },
  {
    Month: '2023-03',
    'Data Scientist': 38,
    'Data Engineer': 28,
    'Data Analyst': 90,
    'ML Engineer': 1,
  },
  {
    Month: '2023-04',
    'Data Scientist': 38,
    'Data Engineer': 27,
    'Data Analyst': 83,
    'ML Engineer': 2,
  },
  {
    Month: '2023-05',
    'Data Scientist': 41,
    'Data Engineer': 28,
    'Data Analyst': 87,
    'ML Engineer': 2,
  },
  {
    Month: '2023-06',
    'Data Scientist': 40,
    'Data Engineer': 30,
    'Data Analyst': 91,
    'ML Engineer': 2,
  },
  {
    Month: '2023-07',
    'Data Scientist': 39,
    'Data Engineer': 32,
    'Data Analyst': 98,
    'ML Engineer': 2,
  },
  {
    Month: '2023-08',
    'Data Scientist': 50,
    'Data Engineer': 34,
    'Data Analyst': 95,
    'ML Engineer': 2,
  },
  {
    Month: '2023-09',
    'Data Scientist': 42,
    'Data Engineer': 31,
    'Data Analyst': 91,
    'ML Engineer': 2,
  },
  {
    Month: '2023-10',
    'Data Scientist': 37,
    'Data Engineer': 30,
    'Data Analyst': 86,
    'ML Engineer': 2,
  },
  {
    Month: '2023-11',
    'Data Scientist': 35,
    'Data Engineer': 29,
    'Data Analyst': 82,
    'ML Engineer': 2,
  },
  {
    Month: '2023-12',
    'Data Scientist': 34,
    'Data Engineer': 27,
    'Data Analyst': 78,
    'ML Engineer': 2,
  },
  {
    Month: '2024-01',
    'Data Scientist': 41,
    'Data Engineer': 34,
    'Data Analyst': 100,
    'ML Engineer': 2,
  },
  {
    Month: '2024-02',
    'Data Scientist': 41,
    'Data Engineer': 36,
    'Data Analyst': 99,
    'ML Engineer': 3,
  },
  {
    Month: '2024-03',
    'Data Scientist': 40,
    'Data Engineer': 34,
    'Data Analyst': 91,
    'ML Engineer': 3,
  },
];
